// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet/v1/greet.proto

package bitbucket.com.mightnvi.grpcgoex;

public final class Greet {
  private Greet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GreetRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:greet.v1.GreetRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();
  }
  /**
   * Protobuf type {@code greet.v1.GreetRequest}
   */
  public static final class GreetRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:greet.v1.GreetRequest)
      GreetRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GreetRequest.newBuilder() to construct.
    private GreetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GreetRequest() {
      name_ = "";
      title_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GreetRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bitbucket.com.mightnvi.grpcgoex.Greet.internal_static_greet_v1_GreetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bitbucket.com.mightnvi.grpcgoex.Greet.internal_static_greet_v1_GreetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest.class, bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest)) {
        return super.equals(obj);
      }
      bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest other = (bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code greet.v1.GreetRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:greet.v1.GreetRequest)
        bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bitbucket.com.mightnvi.grpcgoex.Greet.internal_static_greet_v1_GreetRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bitbucket.com.mightnvi.grpcgoex.Greet.internal_static_greet_v1_GreetRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest.class, bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest.Builder.class);
      }

      // Construct using bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        title_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bitbucket.com.mightnvi.grpcgoex.Greet.internal_static_greet_v1_GreetRequest_descriptor;
      }

      @java.lang.Override
      public bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest getDefaultInstanceForType() {
        return bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest.getDefaultInstance();
      }

      @java.lang.Override
      public bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest build() {
        bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest buildPartial() {
        bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest result = new bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.title_ = title_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest) {
          return mergeFrom((bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest other) {
        if (other == bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:greet.v1.GreetRequest)
    }

    // @@protoc_insertion_point(class_scope:greet.v1.GreetRequest)
    private static final bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest();
    }

    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GreetRequest>
        PARSER = new com.google.protobuf.AbstractParser<GreetRequest>() {
      @java.lang.Override
      public GreetRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GreetRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GreetRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bitbucket.com.mightnvi.grpcgoex.Greet.GreetRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GreetResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:greet.v1.GreetResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional int32 char_length = 2;</code>
     * @return Whether the charLength field is set.
     */
    boolean hasCharLength();
    /**
     * <code>optional int32 char_length = 2;</code>
     * @return The charLength.
     */
    int getCharLength();

    /**
     * <code>.google.protobuf.Timestamp current_time = 3;</code>
     * @return Whether the currentTime field is set.
     */
    boolean hasCurrentTime();
    /**
     * <code>.google.protobuf.Timestamp current_time = 3;</code>
     * @return The currentTime.
     */
    com.google.protobuf.Timestamp getCurrentTime();
    /**
     * <code>.google.protobuf.Timestamp current_time = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCurrentTimeOrBuilder();
  }
  /**
   * Protobuf type {@code greet.v1.GreetResponse}
   */
  public static final class GreetResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:greet.v1.GreetResponse)
      GreetResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GreetResponse.newBuilder() to construct.
    private GreetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GreetResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GreetResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bitbucket.com.mightnvi.grpcgoex.Greet.internal_static_greet_v1_GreetResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bitbucket.com.mightnvi.grpcgoex.Greet.internal_static_greet_v1_GreetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse.class, bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHAR_LENGTH_FIELD_NUMBER = 2;
    private int charLength_ = 0;
    /**
     * <code>optional int32 char_length = 2;</code>
     * @return Whether the charLength field is set.
     */
    @java.lang.Override
    public boolean hasCharLength() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 char_length = 2;</code>
     * @return The charLength.
     */
    @java.lang.Override
    public int getCharLength() {
      return charLength_;
    }

    public static final int CURRENT_TIME_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp currentTime_;
    /**
     * <code>.google.protobuf.Timestamp current_time = 3;</code>
     * @return Whether the currentTime field is set.
     */
    @java.lang.Override
    public boolean hasCurrentTime() {
      return currentTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp current_time = 3;</code>
     * @return The currentTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCurrentTime() {
      return currentTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp current_time = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCurrentTimeOrBuilder() {
      return currentTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(2, charLength_);
      }
      if (currentTime_ != null) {
        output.writeMessage(3, getCurrentTime());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, charLength_);
      }
      if (currentTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCurrentTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse)) {
        return super.equals(obj);
      }
      bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse other = (bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (hasCharLength() != other.hasCharLength()) return false;
      if (hasCharLength()) {
        if (getCharLength()
            != other.getCharLength()) return false;
      }
      if (hasCurrentTime() != other.hasCurrentTime()) return false;
      if (hasCurrentTime()) {
        if (!getCurrentTime()
            .equals(other.getCurrentTime())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (hasCharLength()) {
        hash = (37 * hash) + CHAR_LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getCharLength();
      }
      if (hasCurrentTime()) {
        hash = (37 * hash) + CURRENT_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentTime().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code greet.v1.GreetResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:greet.v1.GreetResponse)
        bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bitbucket.com.mightnvi.grpcgoex.Greet.internal_static_greet_v1_GreetResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bitbucket.com.mightnvi.grpcgoex.Greet.internal_static_greet_v1_GreetResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse.class, bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse.Builder.class);
      }

      // Construct using bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        message_ = "";
        charLength_ = 0;
        currentTime_ = null;
        if (currentTimeBuilder_ != null) {
          currentTimeBuilder_.dispose();
          currentTimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bitbucket.com.mightnvi.grpcgoex.Greet.internal_static_greet_v1_GreetResponse_descriptor;
      }

      @java.lang.Override
      public bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse getDefaultInstanceForType() {
        return bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse.getDefaultInstance();
      }

      @java.lang.Override
      public bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse build() {
        bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse buildPartial() {
        bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse result = new bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.message_ = message_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.charLength_ = charLength_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.currentTime_ = currentTimeBuilder_ == null
              ? currentTime_
              : currentTimeBuilder_.build();
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse) {
          return mergeFrom((bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse other) {
        if (other == bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasCharLength()) {
          setCharLength(other.getCharLength());
        }
        if (other.hasCurrentTime()) {
          mergeCurrentTime(other.getCurrentTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                charLength_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getCurrentTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int charLength_ ;
      /**
       * <code>optional int32 char_length = 2;</code>
       * @return Whether the charLength field is set.
       */
      @java.lang.Override
      public boolean hasCharLength() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 char_length = 2;</code>
       * @return The charLength.
       */
      @java.lang.Override
      public int getCharLength() {
        return charLength_;
      }
      /**
       * <code>optional int32 char_length = 2;</code>
       * @param value The charLength to set.
       * @return This builder for chaining.
       */
      public Builder setCharLength(int value) {
        
        charLength_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 char_length = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCharLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        charLength_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp currentTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> currentTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp current_time = 3;</code>
       * @return Whether the currentTime field is set.
       */
      public boolean hasCurrentTime() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp current_time = 3;</code>
       * @return The currentTime.
       */
      public com.google.protobuf.Timestamp getCurrentTime() {
        if (currentTimeBuilder_ == null) {
          return currentTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentTime_;
        } else {
          return currentTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp current_time = 3;</code>
       */
      public Builder setCurrentTime(com.google.protobuf.Timestamp value) {
        if (currentTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          currentTime_ = value;
        } else {
          currentTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp current_time = 3;</code>
       */
      public Builder setCurrentTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (currentTimeBuilder_ == null) {
          currentTime_ = builderForValue.build();
        } else {
          currentTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp current_time = 3;</code>
       */
      public Builder mergeCurrentTime(com.google.protobuf.Timestamp value) {
        if (currentTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            currentTime_ != null &&
            currentTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCurrentTimeBuilder().mergeFrom(value);
          } else {
            currentTime_ = value;
          }
        } else {
          currentTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp current_time = 3;</code>
       */
      public Builder clearCurrentTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        currentTime_ = null;
        if (currentTimeBuilder_ != null) {
          currentTimeBuilder_.dispose();
          currentTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp current_time = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCurrentTimeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCurrentTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp current_time = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCurrentTimeOrBuilder() {
        if (currentTimeBuilder_ != null) {
          return currentTimeBuilder_.getMessageOrBuilder();
        } else {
          return currentTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : currentTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp current_time = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCurrentTimeFieldBuilder() {
        if (currentTimeBuilder_ == null) {
          currentTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCurrentTime(),
                  getParentForChildren(),
                  isClean());
          currentTime_ = null;
        }
        return currentTimeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:greet.v1.GreetResponse)
    }

    // @@protoc_insertion_point(class_scope:greet.v1.GreetResponse)
    private static final bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse();
    }

    public static bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GreetResponse>
        PARSER = new com.google.protobuf.AbstractParser<GreetResponse>() {
      @java.lang.Override
      public GreetResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GreetResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GreetResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bitbucket.com.mightnvi.grpcgoex.Greet.GreetResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greet_v1_GreetRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greet_v1_GreetRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greet_v1_GreetResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greet_v1_GreetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024greet/v1/greet.proto\022\010greet.v1\032\037google" +
      "/protobuf/timestamp.proto\"+\n\014GreetReques" +
      "t\022\014\n\004name\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\"|\n\rGreetR" +
      "esponse\022\017\n\007message\030\001 \001(\t\022\030\n\013char_length\030" +
      "\002 \001(\005H\000\210\001\001\0220\n\014current_time\030\003 \001(\0132\032.googl" +
      "e.protobuf.TimestampB\016\n\014_char_length2\251\002\n" +
      "\014GreetService\022=\n\nGreetUnary\022\026.greet.v1.G" +
      "reetRequest\032\027.greet.v1.GreetResponse\022F\n\021" +
      "GreetClientStream\022\026.greet.v1.GreetReques" +
      "t\032\027.greet.v1.GreetResponse(\001\022G\n\022GreetSer" +
      "viceStream\022\026.greet.v1.GreetRequest\032\027.gre" +
      "et.v1.GreetResponse0\001\022I\n\022GreetBidirectio" +
      "nal\022\026.greet.v1.GreetRequest\032\027.greet.v1.G" +
      "reetResponse(\0010\001BQ\n\037bitbucket.com.mightn" +
      "vi.grpcgoexZ.bitbucket.com/mightnvi/grpc" +
      "-go-ex/server/protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_greet_v1_GreetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_greet_v1_GreetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greet_v1_GreetRequest_descriptor,
        new java.lang.String[] { "Name", "Title", });
    internal_static_greet_v1_GreetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_greet_v1_GreetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greet_v1_GreetResponse_descriptor,
        new java.lang.String[] { "Message", "CharLength", "CurrentTime", "CharLength", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
